[LOCATIONS]
input_folder = ./input/videos
output_folder = ./output/video_segments
transcripts_folder = ./output/transcripts
refined_transcripts_folder = ./output/refined_transcripts
audio_folder = ./output/audio
logs_folder = ./output/logs

# The existing code setup uses a mongodb database to store the processed data.
[DATABASE]
host = localhost
port = 27017
db_name = videoEnhancedLearning # create your own file

[OPENAI]
api_key = YOUR_API_KEY_HERE  # Replace this with your actual key
model = gpt-4o 

[PROCESSING]
transcription_model = tiny # example values - configure 
chunk_length_ms = 30000 # example values - configure               
retry_attempts = 5 # example values - configure                 
retry_delay = 60 # example values - configure 

[FILES]
# Patterns for processing multiple videos
video_files = example.mp4 # Give 1 or more files as in input to the video processing file with comma seperated values. 
